Ad user agent:
outscale-dev/cluster-api-provider-outscale pull request #112
Opened 2022-10-03 08:35 UTC by outscale-vbr

* add user agent
* add version
* add version test

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

2022-10-04 12:26 UTC, outscale-hmi reviewed
OK

2022-10-05 13:41 UTC, outscale-mdr commented on Makefile
> +LDFLAGS ?= "-X ${PKG}/pkg/util.capoVersion=${RELEASE_TAG} -X ${PKG}/pkg/util.gitCommit=${GIT_COMMIT} -X ${PKG}/pkg/util.buildDate=${BUILD_DATE}"
Where do you initialized  "PKG" ?

2022-10-05 13:41 UTC, outscale-mdr commented on cloud/scope/clients.go
> +	"github.com/outscale-dev/cluster-api-provider-outscale.git/util/reconciler"
".git" ? Oh it is in your module name

2022-10-05 13:41 UTC, outscale-mdr commented on util/reconciler/version_test.go
> +	}
I don't see the use of this test, why do you want to test this feature ?

2022-10-06 10:59 UTC, outscale-vbr commented on Makefile
> +LDFLAGS ?= "-X ${PKG}/pkg/util.capoVersion=${RELEASE_TAG} -X ${PKG}/pkg/util.gitCommit=${GIT_COMMIT} -X ${PKG}/pkg/util.buildDate=${BUILD_DATE}"
Done

2022-10-06 12:35 UTC, outscale-mdr requested changes

2022-10-06 12:35 UTC, outscale-mdr commented on Makefile
> +PKG := github.com/outscale-dev/cluster-api-provider-outscale
I think there is a ".git" at the end

2022-10-06 12:35 UTC, outscale-mdr commented on Makefile
> +PKG := github.com/outscale-dev/cluster-api-provider-outscale
Can you confim that the user-agent is changed, you can see that in the logs

2022-10-06 12:35 UTC, outscale-mdr commented on util/reconciler/version_test.go
> +	}
What do you think, is it useful ?

2022-10-07 12:19 UTC, outscale-hmi reviewed
OK

2022-10-07 12:19 UTC, outscale-hmi commented on cloud/scope/clients.go
>  		auth: context.WithValue(context.Background(), osc.ContextAWSv4, osc.AWSv4{
we have a helper to get creds from env variables or from json file: 
NewConfigEnv() or NewConfigFile , and then methods for configuration() and context() to get creds properly.

2022-10-07 12:49 UTC, outscale-hmi approved these changes
OK

2022-10-07 14:25 UTC, merged

2022-10-09 12:10 UTC, outscale-vbr commented
Closes https://github.com/outscale-dev/cluster-api-provider-outscale/issues/2