Check httpRes is not nil
outscale-dev/cluster-api-provider-outscale pull request #201
Opened 2022-12-07 08:50 UTC by outscale-vbr

**What type of PR is this?**
/kind bug 

**What this PR does / why we need it**:
Check httpRes is not nul and return error otherwise.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
#199 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

2022-12-08 17:38 UTC, outscale-vbr commented
@outscale-mdr @outscale-hmi   I supposed that every api call can not return http status.

2022-12-08 17:39 UTC, outscale-vbr commented
Closes #199

2022-12-12 08:23 UTC, outscale-vbr commented
@outscale-mdr @outscale-hmi Are you ok with the latest version ?

2022-12-12 08:51 UTC, outscale-mdr requested changes

2022-12-12 08:51 UTC, outscale-mdr commented on cloud/services/compute/image.go
> +			return nil, err
You shoud return the error and not Printf

```fmt.Errorf("error %s httpRes %s", err, httpRes.Status)```

2022-12-12 08:51 UTC, outscale-mdr commented on cloud/services/compute/image.go
> +		}
No need to specify "with empty Res", just return the error

2022-12-13 12:39 UTC, outscale-vbr commented
@outscale-mdr Are you ok with latest changes

2022-12-13 13:13 UTC, outscale-mdr approved these changes
Do not forget the doc :)

2022-12-13 13:28 UTC, outscale-vbr commented
@outscale-mdr Thanks i add the docs.

2022-12-13 15:50 UTC, merged